# Now using separate compose files for dev and production

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8080:8080
      - 9001:9001
    restart: unless-stopped



  mocked-gpio:
    container_name: mocked-gpio
    environment:
      - MQTT_HOSTNAME=mosquitto
      - MOCK_NUMBER_OF_DRIVERS=6
    build: 
      context: ./gpio
      dockerfile: Dockerfile.Mocked 
    depends_on:
      - mosquitto
    restart: unless-stopped


  lapdata:
    container_name: lapdata
    environment:
      - MQTT_HOSTNAME=mosquitto
      - MINIMUM_LAP_TIME=2
    build: ./lapdata
    depends_on:
      - mocked-gpio
    restart: unless-stopped
    

  react:
    container_name: react
    build: 
      context: ./react
      dockerfile: Dockerfile.dev
    volumes:
      - ./react/src:/app/src
      - react_node_modules:/app/node_modules # this anonymous volume prevents the local directory from overwriting the container's node_modules directory.
    ports:
      - 8088:5173
    #environment variables cannot be used directly by a react app, though Vite can be used to read them and compile them into the app
    environment:
      - VITE_CIRCUIT_NAME=Wellington Raceway
      - VITE_MQTT_URL=ws://localhost:8080
      - VITE_API_URL=http://localhost:8000
      - VITE_CAR_MEDIA_FOLDER=media/cars


  api:
    container_name: api
    environment:
      - API_URL=http://localhost:8000   # as seen by external users including the react app
      - REACT_URL=http://localhost:8088
      - MEDIA_FOLDER=media
      - CARS_MEDIA_FOLDER=media/cars
      - DB_DATABASE=lapcounter_server
      - DB_USER=lap
      - DB_PASSWORD=lap
      - DB_HOST=database
      - DB_PORT=5432
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/app:/usr/src/app
    ports:
      - "8000:8000"


  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: lapcounter_server
      POSTGRES_USER: lap
      POSTGRES_PASSWORD: lap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: youremail@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"

  #nginx-proxy-manager:
  #  image: 'jc21/nginx-proxy-manager:latest'
  #  restart: unless-stopped
  #  ports:
  #    # These ports are in format <host-port>:<container-port>
  #    - '80:80' # Public HTTP Port
  #    - '443:443' # Public HTTPS Port
  #    - '81:81' # Admin Web Port
  #  volumes:
  #    - ./data:/data
  #    - ./letsencrypt:/etc/letsencrypt

  test-mqtt-latency:
    profiles: ["disabled"]
    image: gregkwoods/lapcounter-server-test-mqtt-latency:latest
    build: ./test-mqtt-latency
    container_name: test-mqtt-latency
    environment: 
      - MQTT_HOSTNAME=mosquitto
    depends_on:
      - mosquitto


  portainer:
    profiles: ["disabled"]
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
        #- 9443:9443
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
 

volumes:
  postgres_data:
  react_node_modules:
