# When running in production, be sure to set envuronment variables with the --env-file argument
#  e.g. 
# docker compose up --profile test --env-file .env.production



services:

  mosquitto:
    profiles: ["dev", "production"]
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8080:8080
      - 9001:9001
    restart: unless-stopped


  lapcounter-server-gpio-lane1:
    profiles: ["production"]
    image: gregkwoods/lapcounter-server-gpio:latest
    env_file:
      - .env.docker
    environment:
      - LANE_NUMBER=1
    build: ./lapcounter-server-gpio
    container_name: lapcounter-server-gpio-1
    privileged: true
    depends_on:
      - mosquitto  


  lapcounter-server-gpio-lane2:
    profiles: ["production"]
    image: gregkwoods/lapcounter-server-gpio:latest
    env_file:
      - .env.docker
    environment:
      - LANE_NUMBER=2
    build: ./lapcounter-server-gpio
    container_name: lapcounter-server-gpio-2
    privileged: true
    depends_on:
      - mosquitto


  lapcounter-server-mocked-gpio:
    profiles: ["dev"]
    image: gregkwoods/lapcounter-server-mocked-gpio:latest
    build: 
      context: ./lapcounter-server-gpio
      dockerfile: Dockerfile.Mock
    env_file:
      - .env.docker
    container_name: lapcounter-server-mocked-gpio
    depends_on:
      - mosquitto


  lapcounter-server-lapdata:
    profiles: ["dev", "production"]
    image: gregkwoods/lapcounter-server-lapdata:latest
    env_file:
      - .env.docker
    build: ./lapcounter-server-lapdata
    container_name: lapcounter-server-lapdata
    depends_on:
      - lapcounter-server-gpio-lane1


  lapcounter-web:
    profiles: ["dev", "production"]
    image: gregkwoods/lapcounter-web:latest
    ports:
      - 8090:80
    build: ./lapcounter-web
    container_name: lapcounter-web
    depends_on:
      - lapcounter-server-lapdata


  #nginx-proxy-manager:
  #  profiles: ["dev", "production"]
  #  image: 'jc21/nginx-proxy-manager:latest'
  #  restart: unless-stopped
  #  ports:
  #    # These ports are in format <host-port>:<container-port>
  #    - '80:80' # Public HTTP Port
  #    - '443:443' # Public HTTPS Port
  #    - '81:81' # Admin Web Port
  #  volumes:
  #    - ./data:/data
  #    - ./letsencrypt:/etc/letsencrypt



  lapcounter-server-test-mqtt-latency:
    profiles: ["disabled"]
    env_file:
      - .env.docker
    image: gregkwoods/lapcounter-server-test-mqtt-latency:latest
    build: ./lapcounter-server-test-mqtt-latency
    container_name: lapcounter-server-test-mqtt-latency
    depends_on:
      - mosquitto


  portainer:
    profiles: ["disabled"]
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
        #- 9443:9443
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock


# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

