# Now using separate compose files for dev and production

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    env_file:
      - ./.env.development
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8080:8080
      - 9001:9001
    restart: unless-stopped



  mocked-gpio:
    container_name: mocked-gpio
    environment:
      - MQTT_HOSTNAME="mosquitto"
    build: 
      context: ./gpio
      dockerfile: Dockerfile.Mocked 
    depends_on:
      - mosquitto
    restart: unless-stopped


  lapdata:
    container_name: lapdata
    environment:
      - MQTT_HOSTNAME="localhost"
      - MINIMUM_LAP_TIME="2"
    build: ./lapdata
    depends_on:
      - mocked-gpio
    restart: unless-stopped


  api:
    container_name: api
    environment:
      - API_URL="http://localhost:8000"
      - REACT_URL="http://localhost:8080"
      - MEDIA_FOLDER="/media"
      - CARS_MEDIA_FOLDER="/media/cars"    
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/app:/usr/src/app
    ports:
      - "8000:8000"

    

  react:
    container_name: react
    #environment variables are useless to a react app, though Vite can be used to read them and compile them into the app
    build: 
      context: ./react
      dockerfile: Dockerfile.dev
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - 8088:5173




  #nginx-proxy-manager:
  #  image: 'jc21/nginx-proxy-manager:latest'
  #  restart: unless-stopped
  #  ports:
  #    # These ports are in format <host-port>:<container-port>
  #    - '80:80' # Public HTTP Port
  #    - '443:443' # Public HTTPS Port
  #    - '81:81' # Admin Web Port
  #  volumes:
  #    - ./data:/data
  #    - ./letsencrypt:/etc/letsencrypt

  test-mqtt-latency:
    profiles: ["disabled"]
    env_file:
      - .env.development
    image: gregkwoods/lapcounter-server-test-mqtt-latency:latest
    build: ./test-mqtt-latency
    container_name: test-mqtt-latency
    depends_on:
      - mosquitto


  portainer:
    profiles: ["disabled"]
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
        #- 9443:9443
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
