services:

  #lapcounter-server-gpio:
  #  profiles: ["test", "production"]
  #  #image: gregwoods/lapcounter-server-gpio:0.1.0
  #  build: ./lapcounter-server-gpio
  #  container_name: lapcounter-server-gpio
  #  privileged: true 
  #  #ports:
  #  #  - 8008:8008


  lapcounter-server-lapdata:
    profiles: ["dev"]
    #image: gregwoods/lapcounter-server-lapdata:0.1.0
    build: ./lapcounter-server-lapdata
    container_name: lapcounter-server-lapdata
    #ports:
    #  - 8009:8009


  mosquitto:
    profiles: ["dev", "test", "production"]
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped


  #TODO: try profiles to be able to disable this in production
  portainer:
    profiles: ["test"]
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
        #- 9443:9443
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock



# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

