#

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8080:8080
      - 9001:9001
    restart: unless-stopped

  gpio-lane1:
    image: gregkwoods/lapcounter-server-gpio:latest
    pull_policy: always
    env_file:
      - .env.prod
    environment:
      - LANE_NUMBER=1
    build: ./gpio
    container_name: gpio-1
    privileged: true
    restart: unless-stopped
    depends_on:
      - mosquitto  


  gpio-lane2:
    image: gregkwoods/lapcounter-server-gpio:latest
    pull_policy: always
    env_file:
      - .env.prod
    environment:
      - LANE_NUMBER=2
    build: ./gpio
    container_name: gpio-2
    privileged: true
    restart: unless-stopped
    depends_on:
      - gpio-lane1


  lapdata:
    image: gregkwoods/lapcounter-server-lapdata:latest
    pull_policy: always
    env_file:
      - .env.prod
    build: ./lapdata
    container_name: lapdata
    restart: unless-stopped
    depends_on:
      - gpio-lane2


  web:
    profiles: ["disabled"]
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    image: gregkwoods/lapcounter-server-web:latest
    pull_policy: always
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  react:
    build: ./react
    container_name: react
    image: gregkwoods/lapcounter-server-react:latest
    pull_policy: always
    ports:
      - 8087:80
    volumes:
      - static_volume:/usr/src/app/dist
    #for debugging. Use docker compose "run" instead of "up"
    #restart: unless-stopped
    #entrypoint: /bin/sh

  #web:
  #  container_name: web
  #  build: ./web
  #  image: gregkwoods/lapcounter-server-web:latest
  #  command: python manage.py run -h 0.0.0.0
  #  volumes:
  #    - ./web:/usr/src/app
  #  ports:
  #    - 5001:5000
  #  env_file:
  #    - ./.env.dev
  #  depends_on:
  #    - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.fastAPI.prod
    ports:
      - "8000:8000"
    #env_file:
    #  - ./api/.env.prod
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBUFFERED=1


  nginx:
    profiles: ["disabled"]
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1337:80


  db:
    profiles: ["disabled"]
    container_name: db
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
