# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json package-lock.json vite.config.js index.html ./
RUN npm ci

COPY ./src ./src
COPY ./public ./public

# Start the development server
CMD ["npm", "run", "dev"]