# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json vite.config.js index.html ./
COPY ./src ./src
COPY ./public ./public

RUN npm ci

# Start the development server
CMD ["npm", "run", "dev"]