FROM python:3.12.8-bookworm

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1


COPY ./app/requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
COPY ./app/. /usr/src/app/

CMD ["fastapi", "run", "main.py"]


# Interactive build
#RUN apt-get update && apt-get install -y \
# curl \ 
# vim
#CMD ["bash"]
