FROM python:3.12.8-bookworm

WORKDIR /usr/src/app

COPY ./app/requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./app/. /usr/src/app/

CMD ["fastapi", "dev", "--host", "0.0.0.0", "/usr/src/app/main/main.py"]
